name: Deploy to Server

on:
  push:
    branches: [feature]

env:
  SSH_PORT: 22
  PROJECT_DIR: /home/ermin

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Go
        run: |
          cd ./backend
          go fmt
          go vet
      - name: Lint JS
        run: |
          cd ./frontend
          npm install && npm run lint
  deploy:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd Glorbo && docker compose down
            cd .. && rm -rf Glorbo
            git clone --branch feature https://github.com/magnoliAHAH/Glorbo.git
            cd Glorbo
            docker compose up -d --build
