name: Deploy to Server

on:
  push:
    branches: [main]

env:
  SSH_PORT: 22
  PROJECT_DIR: /home/ermin # Путь на сервере

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Add SSH Known Hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "optional"

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ env.SSH_PORT }}
          source: "."
          target: ${{ env.PROJECT_DIR }}
          rm: true

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ env.SSH_PORT }}
          script: |
            cd ${{ env.PROJECT_DIR }}
            docker compose down
            docker compose up -d --build
