name: Deploy to Server

on:
  push:
    branches: [main]

env:
  SSH_PORT: 22
  PROJECT_DIR: /home/ermin # Путь на сервере

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd Glorbo && docker compose down
            cd .. && rm -rf Glorbo
            git clone https://github.com/magnoliAHAH/Glorbo.git
            cd Glorbo
            docker compose up -d --build
