name: Deploy to Server

on:
  push:
    branches: [main]

env:
  SSH_PORT: 22
  PROJECT_DIR: /home/ermin # Путь на сервере

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/deploy/app
            cd /home/deploy/app
            if [ -d .git ]; then
              git pull
            else
              git clone https://github.com/magnoliAHAH/Glorbo.git .
            fi
            docker compose up -d --build
