name: Deploy to Server

on:
  push:
    branches: [k3s]

env:
  SSH_PORT: 22
  PROJECT_DIR: /root

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_K3S_HOST }}
          username: ${{ secrets.SSH_K3S_USERNAME }}
          key: ${{ secrets.SSH_K3S_PRIVATE_KEY }}
          script: |
            rm -rf Glorbo
            git clone --branch k3s https://github.com/magnoliAHAH/Glorbo.git
            cd ~/Glorbo/backend/
            docker build -t glorbo-backend:latest .
            docker tag glorbo-backend:latest mixail.ermin33.fvds.ru:31339/glorbo-backend:latest
            cd ~/Glorbo/frontend/
            docker build -t glorbo-frontend:latest .
            docker tag glorbo-frontend:latest mixail.ermin33.fvds.ru:31339/glorbo-frontend:latest
            kubectl apply -f ~/Glorbo/k3s-setup/
