name: Deploy to Server

on:
  push:
    branches: [k3s]

env:
  KUBERNETES_NAMESPACE: glorbo-app
  REGISTRY_URL: mixail.ermin33.fvds.ru:31339

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY_URL: mixail.ermin33.fvds.ru:31339
      KUBERNETES_NAMESPACE: glorbo-app
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        env:
          REGISTRY_URL: ${{ env.REGISTRY_URL }}
          KUBERNETES_NAMESPACE: ${{ env.KUBERNETES_NAMESPACE }}
        with:
          host: ${{ secrets.SSH_K3S_HOST }}
          username: ${{ secrets.SSH_K3S_USERNAME }}
          key: ${{ secrets.SSH_K3S_PRIVATE_KEY }}
          script: |
            rm -rf Glorbo
            git clone --branch k3s https://github.com/magnoliAHAH/Glorbo.git

            cd Glorbo/backend
            docker build -t $REGISTRY_URL/glorbo-backend:latest .
            docker push $REGISTRY_URL/glorbo-backend:latest

            cd ../frontend
            docker build -t $REGISTRY_URL/glorbo-frontend:latest .
            docker push $REGISTRY_URL/glorbo-frontend:latest

            cd ../k3s-setup
            sed -i "s|image: $REGISTRY_URL/glorbo-backend:.*|image: $REGISTRY_URL/glorbo-backend:latest|" backend-deploy.yaml
            sed -i "s|image: $REGISTRY_URL/glorbo-frontend:.*|image: $REGISTRY_URL/glorbo-frontend:latest|" frontend-deploy.yaml

            kubectl apply -f backend-deploy.yaml -n $KUBERNETES_NAMESPACE
            kubectl rollout status deployment/backend -n $KUBERNETES_NAMESPACE

            kubectl apply -f frontend-deploy.yaml -n $KUBERNETES_NAMESPACE
            kubectl rollout status deployment/frontend -n $KUBERNETES_NAMESPACE
